## WithColumn 1/2

In [ ]:
# 1. Criar um dataframe para ler o arquivo no HDFS /user/<nome/data/juros_selic/juros_selic

In [3]:
! hdfs dfs -cat /user/daniel/data/exercises-data/juros_selic/juros_selic

"data";"valor"
"01/06/1986";"1,27"
"01/07/1986";"1,95"
"01/08/1986";"2,57"
"01/09/1986";"2,94"
"01/10/1986";"1,96"
"01/11/1986";"2,37"
"01/12/1986";"5,47"
"01/01/1987";"11,00"
"01/02/1987";"19,61"
"01/03/1987";"11,95"
"01/04/1987";"15,30"
"01/05/1987";"24,63"
"01/06/1987";"18,02"
"01/07/1987";"8,91"
"01/08/1987";"8,09"
"01/09/1987";"7,99"
"01/10/1987";"9,45"
"01/11/1987";"12,92"
"01/12/1987";"14,38"
"01/01/1988";"16,78"
"01/02/1988";"18,35"
"01/03/1988";"16,59"
"01/04/1988";"20,25"
"01/05/1988";"18,65"
"01/06/1988";"20,17"
"01/07/1988";"24,69"
"01/08/1988";"22,63"
"01/09/1988";"26,25"
"01/10/1988";"29,79"
"01/11/1988";"28,41"
"01/12/1988";"30,24"
"01/01/1989";"22,97"
"01/02/1989";"18,95"
"01/03/1989";"20,41"
"01/04/1989";"11,52"
"01/05/1989";"11,43"
"01/06/1989";"27,29"
"01/07/1989";"33,15"
"01/08/1989";"35,49"
"01/09/1989";"38,58"
"01/10/1989";"47,70"
"01/11/1989";"48,41"
"01/12/1989";"64,21"
"01/01/1990";"67,60"
"01/02/1990";"82,04"
"01/03/1990";"36,76"
"01/04/1990";"4,23"
"01/05/1990";"5,69"
"01/06/1990";"8,73"
"01/07/1990";"13,79"
"01/08/1990";"11,53"
"01/09/1990";"15,21"
"01/10/1990";"16,49"
"01/11/1990";"19,83"
"01/12/1990";"22,86"
"01/01/1991";"21,02"
"01/02/1991";"6,85"
"01/03/1991";"8,99"
"01/04/1991";"9,67"
"01/05/1991";"9,56"
"01/06/1991";"10,32"
"01/07/1991";"12,39"
"01/08/1991";"15,75"
"01/09/1991";"19,78"
"01/10/1991";"25,95"
"01/11/1991";"32,43"
"01/12/1991";"31,17"
"01/01/1992";"29,06"
"01/02/1992";"28,76"
"01/03/1992";"26,86"
"01/04/1992";"23,92"
"01/05/1992";"23,00"
"01/06/1992";"24,28"
"01/07/1992";"26,21"
"01/08/1992";"25,65"
"01/09/1992";"27,66"
"01/10/1992";"28,18"
"01/11/1992";"26,40"
"01/12/1992";"25,92"
"01/01/1993";"28,52"
"01/02/1993";"28,90"
"01/03/1993";"28,36"
"01/04/1993";"30,53"
"01/05/1993";"30,90"
"01/06/1993";"31,91"
"01/07/1993";"32,73"
"01/08/1993";"34,64"
"01/09/1993";"37,23"
"01/10/1993";"38,40"
"01/11/1993";"38,38"
"01/12/1993";"40,38"
"01/01/1994";"42,76"
"01/02/1994";"41,99"
"01/03/1994";"46,42"
"01/04/1994";"46,49"
"01/05/1994";"47,95"
"01/06/1994";"50,62"
"01/07/1994";"6,87"
"01/08/1994";"4,17"
"01/09/1994";"3,83"
"01/10/1994";"3,62"
"01/11/1994";"4,07"
"01/12/1994";"3,80"
"01/01/1995";"3,37"
"01/02/1995";"3,25"
"01/03/1995";"4,26"
"01/04/1995";"4,26"
"01/05/1995";"4,25"
"01/06/1995";"4,04"
"01/07/1995";"4,02"
"01/08/1995";"3,84"
"01/09/1995";"3,32"
"01/10/1995";"3,09"
"01/11/1995";"2,88"
"01/12/1995";"2,78"
"01/01/1996";"2,58"
"01/02/1996";"2,35"
"01/03/1996";"2,22"
"01/04/1996";"2,07"
"01/05/1996";"2,01"
"01/06/1996";"1,98"
"01/07/1996";"1,93"
"01/08/1996";"1,97"
"01/09/1996";"1,90"
"01/10/1996";"1,86"
"01/11/1996";"1,80"
"01/12/1996";"1,80"
"01/01/1997";"1,73"
"01/02/1997";"1,67"
"01/03/1997";"1,64"
"01/04/1997";"1,66"
"01/05/1997";"1,58"
"01/06/1997";"1,61"
"01/07/1997";"1,60"
"01/08/1997";"1,59"
"01/09/1997";"1,59"
"01/10/1997";"1,67"
"01/11/1997";"3,04"
"01/12/1997";"2,97"
"01/01/1998";"2,67"
"01/02/1998";"2,13"
"01/03/1998";"2,20"
"01/04/1998";"1,71"
"01/05/1998";"1,63"
"01/06/1998";"1,60"
"01/07/1998";"1,70"
"01/08/1998";"1,48"
"01/09/1998";"2,49"
"01/10/1998";"2,94"
"01/11/1998";"2,63"
"01/12/1998";"2,40"
"01/01/1999";"2,18"
"01/02/1999";"2,38"
"01/03/1999";"3,33"
"01/04/1999";"2,35"
"01/05/1999";"2,02"
"01/06/1999";"1,67"
"01/07/1999";"1,66"
"01/08/1999";"1,57"
"01/09/1999";"1,49"
"01/10/1999";"1,38"
"01/11/1999";"1,39"
"01/12/1999";"1,60"
"01/01/2000";"1,46"
"01/02/2000";"1,45"
"01/03/2000";"1,45"
"01/04/2000";"1,30"
"01/05/2000";"1,49"
"01/06/2000";"1,39"
"01/07/2000";"1,31"
"01/08/2000";"1,41"
"01/09/2000";"1,22"
"01/10/2000";"1,29"
"01/11/2000";"1,22"
"01/12/2000";"1,20"
"01/01/2001";"1,27"
"01/02/2001";"1,02"
"01/03/2001";"1,26"
"01/04/2001";"1,19"
"01/05/2001";"1,34"
"01/06/2001";"1,27"
"01/07/2001";"1,50"
"01/08/2001";"1,60"
"01/09/2001";"1,32"
"01/10/2001";"1,53"
"01/11/2001";"1,39"
"01/12/2001";"1,39"
"01/01/2002";"1,53"
"01/02/2002";"1,25"
"01/03/2002";"1,37"
"01/04/2002";"1,48"
"01/05/2002";"1,41"
"01/06/2002";"1,33"
"01/07/2002";"1,54"
"01/08/2002";"1,44"
"01/09/2002";"1,38"
"01/10/2002";"1,65"
"01/11/2002";"1,54"
"01/12/2002";"1,74"
"01/01/2003";"1,97"
"01/02/2003";"1,83"
"01/03/2003";"1,78"
"01/04/2003";"1,87"
"01/05/2003";"1,97"
"01/06/2003";"1,86"
"01/07/2003";"2,08"
"01/08/2003";"1,77"
"01/09/2003";"1,68"
"01/10/2003";"1,64"
"01/11/2003";"1,34"
"01/12/2003";"1,37"
"01/01/2004";"1,27"
"01/02/2004";"1,08"
"01/03/2004";"1,38"
"01/04/2004";"1,18"
"01/05/2004";"1,23"
"01/06/2004";"1,23"
"01/07/2004";"1,29"
"01/08/2004";"1,29"
"01/09/2004";"1,25"
"01/10/2004";"1,21"
"01/11/2004";"1,25"
"01/12/2004";"1,48"
"01/01/2005";"1,38"
"01/02/2005";"1,22"
"01/03/2005";"1,53"
"01/04/2005";"1,41"
"01/05/2005";"1,50"
"01/06/2005";"1,59"
"01/07/2005";"1,51"
"01/08/2005";"1,66"
"01/09/2005";"1,50"
"01/10/2005";"1,41"
"01/11/2005";"1,38"
"01/12/2005";"1,47"
"01/01/2006";"1,43"
"01/02/2006";"1,15"
"01/03/2006";"1,42"
"01/04/2006";"1,08"
"01/05/2006";"1,28"
"01/06/2006";"1,18"
"01/07/2006";"1,17"
"01/08/2006";"1,26"
"01/09/2006";"1,06"
"01/10/2006";"1,09"
"01/11/2006";"1,02"
"01/12/2006";"0,99"
"01/01/2007";"1,08"
"01/02/2007";"0,87"
"01/03/2007";"1,05"
"01/04/2007";"0,94"
"01/05/2007";"1,03"
"01/06/2007";"0,91"
"01/07/2007";"0,97"
"01/08/2007";"0,99"
"01/09/2007";"0,80"
"01/10/2007";"0,93"
"01/11/2007";"0,84"
"01/12/2007";"0,84"
"01/01/2008";"0,93"
"01/02/2008";"0,80"
"01/03/2008";"0,84"
"01/04/2008";"0,90"
"01/05/2008";"0,88"
"01/06/2008";"0,96"
"01/07/2008";"1,07"
"01/08/2008";"1,02"
"01/09/2008";"1,10"
"01/10/2008";"1,18"
"01/11/2008";"1,02"
"01/12/2008";"1,12"
"01/01/2009";"1,05"
"01/02/2009";"0,86"
"01/03/2009";"0,97"
"01/04/2009";"0,84"
"01/05/2009";"0,77"
"01/06/2009";"0,76"
"01/07/2009";"0,79"
"01/08/2009";"0,69"
"01/09/2009";"0,69"
"01/10/2009";"0,69"
"01/11/2009";"0,66"
"01/12/2009";"0,73"
"01/01/2010";"0,66"
"01/02/2010";"0,59"
"01/03/2010";"0,76"
"01/04/2010";"0,67"
"01/05/2010";"0,75"
"01/06/2010";"0,79"
"01/07/2010";"0,86"
"01/08/2010";"0,89"
"01/09/2010";"0,85"
"01/10/2010";"0,81"
"01/11/2010";"0,81"
"01/12/2010";"0,93"
"01/01/2011";"0,86"
"01/02/2011";"0,84"
"01/03/2011";"0,92"
"01/04/2011";"0,84"
"01/05/2011";"0,99"
"01/06/2011";"0,96"
"01/07/2011";"0,97"
"01/08/2011";"1,07"
"01/09/2011";"0,94"
"01/10/2011";"0,88"
"01/11/2011";"0,86"
"01/12/2011";"0,91"
"01/01/2012";"0,89"
"01/02/2012";"0,75"
"01/03/2012";"0,82"
"01/04/2012";"0,71"
"01/05/2012";"0,74"
"01/06/2012";"0,64"
"01/07/2012";"0,68"
"01/08/2012";"0,69"
"01/09/2012";"0,54"
"01/10/2012";"0,61"
"01/11/2012";"0,55"
"01/12/2012";"0,55"
"01/01/2013";"0,60"
"01/02/2013";"0,49"
"01/03/2013";"0,55"
"01/04/2013";"0,61"
"01/05/2013";"0,60"
"01/06/2013";"0,61"
"01/07/2013";"0,72"
"01/08/2013";"0,71"
"01/09/2013";"0,71"
"01/10/2013";"0,81"
"01/11/2013";"0,72"
"01/12/2013";"0,79"
"01/01/2014";"0,85"
"01/02/2014";"0,79"
"01/03/2014";"0,77"
"01/04/2014";"0,82"
"01/05/2014";"0,87"
"01/06/2014";"0,82"
"01/07/2014";"0,95"
"01/08/2014";"0,87"
"01/09/2014";"0,91"
"01/10/2014";"0,95"
"01/11/2014";"0,84"
"01/12/2014";"0,96"
"01/01/2015";"0,94"
"01/02/2015";"0,82"
"01/03/2015";"1,04"
"01/04/2015";"0,95"
"01/05/2015";"0,99"
"01/06/2015";"1,07"
"01/07/2015";"1,18"
"01/08/2015";"1,11"
"01/09/2015";"1,11"
"01/10/2015";"1,11"
"01/11/2015";"1,06"
"01/12/2015";"1,16"
"01/01/2016";"1,06"
"01/02/2016";"1,00"
"01/03/2016";"1,16"
"01/04/2016";"1,06"
"01/05/2016";"1,11"
"01/06/2016";"1,16"
"01/07/2016";"1,11"
"01/08/2016";"1,22"
"01/09/2016";"1,11"
"01/10/2016";"1,05"
"01/11/2016";"1,04"
"01/12/2016";"1,12"
"01/01/2017";"1,09"
"01/02/2017";"0,87"
"01/03/2017";"1,05"
"01/04/2017";"0,79"
"01/05/2017";"0,93"
"01/06/2017";"0,81"
"01/07/2017";"0,80"
"01/08/2017";"0,80"
"01/09/2017";"0,64"
"01/10/2017";"0,64"
"01/11/2017";"0,57"
"01/12/2017";"0,54"
"01/01/2018";"0,58"
"01/02/2018";"0,47"
"01/03/2018";"0,53"
"01/04/2018";"0,52"
"01/05/2018";"0,52"
"01/06/2018";"0,52"
"01/07/2018";"0,54"
"01/08/2018";"0,57"
"01/09/2018";"0,47"
"01/10/2018";"0,54"
"01/11/2018";"0,49"
"01/12/2018";"0,49"
"01/01/2019";"0,54"
"01/02/2019";"0,37"

In [4]:
df = spark.read.csv("/user/daniel/data/exercises-data/juros_selic/juros_selic", sep=";", header="True")

In [5]:
df.show(5)

+----------+-----+
|      data|valor|
+----------+-----+
|01/06/1986| 1,27|
|01/07/1986| 1,95|
|01/08/1986| 2,57|
|01/09/1986| 2,94|
|01/10/1986| 1,96|
+----------+-----+
only showing top 5 rows

In [ ]:
# 2. Alterar o formato do campo data para “MM/dd/yyyy”

In [63]:
from pyspark.sql.functions import col, substring, split, regexp_replace
from pyspark.sql.functions import unix_timestamp, from_unixtime
from pyspark.sql.types import *

In [19]:
formato = df.select("data").show(1)
df_data = df.withColumn("data", unix_timestamp(col("data"), "dd/MM/yyyy"))
df_data = df_data.withColumn("data", from_unixtime("data", "MM/dd/yyyy"))

+----------+
|      data|
+----------+
|01/06/1986|
+----------+
only showing top 1 row

In [20]:
df_data.show(5)

+----------+-----+
|      data|valor|
+----------+-----+
|06/01/1986| 1,27|
|07/01/1986| 1,95|
|08/01/1986| 2,57|
|09/01/1986| 2,94|
|10/01/1986| 1,96|
+----------+-----+
only showing top 5 rows

In [21]:
df_data_direto = df.withColumn("mes-dia-ano", from_unixtime(unix_timestamp(col("data"), "dd/MM/yyyy"), "MM/dd/yyyy"))

In [23]:
df_data_direto.show(5)

+----------+-----+-----------+
|      data|valor|mes-dia-ano|
+----------+-----+-----------+
|01/06/1986| 1,27| 06/01/1986|
|01/07/1986| 1,95| 07/01/1986|
|01/08/1986| 2,57| 08/01/1986|
|01/09/1986| 2,94| 09/01/1986|
|01/10/1986| 1,96| 10/01/1986|
+----------+-----+-----------+
only showing top 5 rows

In [ ]:
# 3. Com uso da função from_unixtime crie o campo “ano_unix”, com a informação do ano do campo data

In [43]:
df_data_ano = df.withColumn("ano_unix", from_unixtime(unix_timestamp(col("data"), "dd/MM/yyyy"), "yyyy"))

In [45]:
df_data_ano.show(5)

+----------+-----+--------+
|      data|valor|ano_unix|
+----------+-----+--------+
|01/06/1986| 1,27|    1986|
|01/07/1986| 1,95|    1986|
|01/08/1986| 2,57|    1986|
|01/09/1986| 2,94|    1986|
|01/10/1986| 1,96|    1986|
+----------+-----+--------+
only showing top 5 rows

In [ ]:
# 4. Com uso de substring crie o campo “ano_str”, com a informação do ano do campo data

In [27]:
df_data_direto = df_data_direto.withColumn("ano_str", substring(col("data"), 7,4))

In [28]:
df_data_direto.show(5)

+----------+-----+-----------+-------+
|      data|valor|mes-dia-ano|ano_str|
+----------+-----+-----------+-------+
|01/06/1986| 1,27| 06/01/1986|   1986|
|01/07/1986| 1,95| 07/01/1986|   1986|
|01/08/1986| 2,57| 08/01/1986|   1986|
|01/09/1986| 2,94| 09/01/1986|   1986|
|01/10/1986| 1,96| 10/01/1986|   1986|
+----------+-----+-----------+-------+
only showing top 5 rows

In [ ]:
# 5. Com uso da função split crie o campo “ano_str”, com a informação do ano do campo data

In [30]:
df_data_direto = df_data_direto.withColumn("data_split", split(col("data"), "/"))

In [31]:
df_data_direto.show(5)

+----------+-----+-----------+-------+--------------+
|      data|valor|mes-dia-ano|ano_str|    data_split|
+----------+-----+-----------+-------+--------------+
|01/06/1986| 1,27| 06/01/1986|   1986|[01, 06, 1986]|
|01/07/1986| 1,95| 07/01/1986|   1986|[01, 07, 1986]|
|01/08/1986| 2,57| 08/01/1986|   1986|[01, 08, 1986]|
|01/09/1986| 2,94| 09/01/1986|   1986|[01, 09, 1986]|
|01/10/1986| 1,96| 10/01/1986|   1986|[01, 10, 1986]|
+----------+-----+-----------+-------+--------------+
only showing top 5 rows

In [32]:
df_data_direto = df_data_direto.withColumn("ano_str_split", col("data_split").getItem(2))

In [36]:
df_data_direto.show(5)

+----------+-----+-----------+-------+--------------+-------------+
|      data|valor|mes-dia-ano|ano_str|    data_split|ano_str_split|
+----------+-----+-----------+-------+--------------+-------------+
|01/06/1986| 1,27| 06/01/1986|   1986|[01, 06, 1986]|         1986|
|01/07/1986| 1,95| 07/01/1986|   1986|[01, 07, 1986]|         1986|
|01/08/1986| 2,57| 08/01/1986|   1986|[01, 08, 1986]|         1986|
|01/09/1986| 2,94| 09/01/1986|   1986|[01, 09, 1986]|         1986|
|01/10/1986| 1,96| 10/01/1986|   1986|[01, 10, 1986]|         1986|
+----------+-----+-----------+-------+--------------+-------------+
only showing top 5 rows

In [39]:
df_data_direto = df_data_direto.drop("data_split")

In [40]:
df_data_direto.show(5)

+----------+-----+-----------+-------+-------------+
|      data|valor|mes-dia-ano|ano_str|ano_str_split|
+----------+-----+-----------+-------+-------------+
|01/06/1986| 1,27| 06/01/1986|   1986|         1986|
|01/07/1986| 1,95| 07/01/1986|   1986|         1986|
|01/08/1986| 2,57| 08/01/1986|   1986|         1986|
|01/09/1986| 2,94| 09/01/1986|   1986|         1986|
|01/10/1986| 1,96| 10/01/1986|   1986|         1986|
+----------+-----+-----------+-------+-------------+
only showing top 5 rows

In [ ]:
# 6. Salvar no hdfs /user/rodrigo/juros_selic_americano no formato CSV, incluindo o cabeçalho

In [41]:
df_data_direto.write.csv("/user/daniel/juros_selic_americano", header=True)

In [46]:
! hdfs dfs -cat /user/daniel/juros_selic_americano/part-00000-ed61139a-e763-4c33-a77d-a2ccf3992907-c000.csv

data,valor,mes-dia-ano,ano_str,ano_str_split
01/06/1986,"1,27",06/01/1986,1986,1986
01/07/1986,"1,95",07/01/1986,1986,1986
01/08/1986,"2,57",08/01/1986,1986,1986
01/09/1986,"2,94",09/01/1986,1986,1986
01/10/1986,"1,96",10/01/1986,1986,1986
01/11/1986,"2,37",11/01/1986,1986,1986
01/12/1986,"5,47",12/01/1986,1986,1986
01/01/1987,"11,00",01/01/1987,1987,1987
01/02/1987,"19,61",02/01/1987,1987,1987
01/03/1987,"11,95",03/01/1987,1987,1987
01/04/1987,"15,30",04/01/1987,1987,1987
01/05/1987,"24,63",05/01/1987,1987,1987
01/06/1987,"18,02",06/01/1987,1987,1987
01/07/1987,"8,91",07/01/1987,1987,1987
01/08/1987,"8,09",08/01/1987,1987,1987
01/09/1987,"7,99",09/01/1987,1987,1987
01/10/1987,"9,45",10/01/1987,1987,1987
01/11/1987,"12,92",11/01/1987,1987,1987
01/12/1987,"14,38",12/01/1987,1987,1987
01/01/1988,"16,78",01/01/1988,1988,1988
01/02/1988,"18,35",02/01/1988,1988,1988
01/03/1988,"16,59",03/01/1988,1988,1988
01/04/1988,"20,25",04/01/1988,1988,1988
01/05/1988,"18,65",05/01/1988,1988,1988
01/06/1988,"20,17",06/01/1988,1988,1988
01/07/1988,"24,69",07/01/1988,1988,1988
01/08/1988,"22,63",08/01/1988,1988,1988
01/09/1988,"26,25",09/01/1988,1988,1988
01/10/1988,"29,79",10/01/1988,1988,1988
01/11/1988,"28,41",11/01/1988,1988,1988
01/12/1988,"30,24",12/01/1988,1988,1988
01/01/1989,"22,97",01/01/1989,1989,1989
01/02/1989,"18,95",02/01/1989,1989,1989
01/03/1989,"20,41",03/01/1989,1989,1989
01/04/1989,"11,52",04/01/1989,1989,1989
01/05/1989,"11,43",05/01/1989,1989,1989
01/06/1989,"27,29",06/01/1989,1989,1989
01/07/1989,"33,15",07/01/1989,1989,1989
01/08/1989,"35,49",08/01/1989,1989,1989
01/09/1989,"38,58",09/01/1989,1989,1989
01/10/1989,"47,70",10/01/1989,1989,1989
01/11/1989,"48,41",11/01/1989,1989,1989
01/12/1989,"64,21",12/01/1989,1989,1989
01/01/1990,"67,60",01/01/1990,1990,1990
01/02/1990,"82,04",02/01/1990,1990,1990
01/03/1990,"36,76",03/01/1990,1990,1990
01/04/1990,"4,23",04/01/1990,1990,1990
01/05/1990,"5,69",05/01/1990,1990,1990
01/06/1990,"8,73",06/01/1990,1990,1990
01/07/1990,"13,79",07/01/1990,1990,1990
01/08/1990,"11,53",08/01/1990,1990,1990
01/09/1990,"15,21",09/01/1990,1990,1990
01/10/1990,"16,49",10/01/1990,1990,1990
01/11/1990,"19,83",11/01/1990,1990,1990
01/12/1990,"22,86",12/01/1990,1990,1990
01/01/1991,"21,02",01/01/1991,1991,1991
01/02/1991,"6,85",02/01/1991,1991,1991
01/03/1991,"8,99",03/01/1991,1991,1991
01/04/1991,"9,67",04/01/1991,1991,1991
01/05/1991,"9,56",05/01/1991,1991,1991
01/06/1991,"10,32",06/01/1991,1991,1991
01/07/1991,"12,39",07/01/1991,1991,1991
01/08/1991,"15,75",08/01/1991,1991,1991
01/09/1991,"19,78",09/01/1991,1991,1991
01/10/1991,"25,95",10/01/1991,1991,1991
01/11/1991,"32,43",11/01/1991,1991,1991
01/12/1991,"31,17",12/01/1991,1991,1991
01/01/1992,"29,06",01/01/1992,1992,1992
01/02/1992,"28,76",02/01/1992,1992,1992
01/03/1992,"26,86",03/01/1992,1992,1992
01/04/1992,"23,92",04/01/1992,1992,1992
01/05/1992,"23,00",05/01/1992,1992,1992
01/06/1992,"24,28",06/01/1992,1992,1992
01/07/1992,"26,21",07/01/1992,1992,1992
01/08/1992,"25,65",08/01/1992,1992,1992
01/09/1992,"27,66",09/01/1992,1992,1992
01/10/1992,"28,18",10/01/1992,1992,1992
01/11/1992,"26,40",11/01/1992,1992,1992
01/12/1992,"25,92",12/01/1992,1992,1992
01/01/1993,"28,52",01/01/1993,1993,1993
01/02/1993,"28,90",02/01/1993,1993,1993
01/03/1993,"28,36",03/01/1993,1993,1993
01/04/1993,"30,53",04/01/1993,1993,1993
01/05/1993,"30,90",05/01/1993,1993,1993
01/06/1993,"31,91",06/01/1993,1993,1993
01/07/1993,"32,73",07/01/1993,1993,1993
01/08/1993,"34,64",08/01/1993,1993,1993
01/09/1993,"37,23",09/01/1993,1993,1993
01/10/1993,"38,40",10/01/1993,1993,1993
01/11/1993,"38,38",11/01/1993,1993,1993
01/12/1993,"40,38",12/01/1993,1993,1993
01/01/1994,"42,76",01/01/1994,1994,1994
01/02/1994,"41,99",02/01/1994,1994,1994
01/03/1994,"46,42",03/01/1994,1994,1994
01/04/1994,"46,49",04/01/1994,1994,1994
01/05/1994,"47,95",05/01/1994,1994,1994
01/06/1994,"50,62",06/01/1994,1994,1994
01/07/1994,"6,87",07/01/1994,1994,1994
01/08/1994,"4,17",08/01/1994,1994,1994
01/09/1994,"3,83",09/01/1994,1994,1994
01/10/1994,"3,62",10/01/1994,1994,1994
01/11/1994,"4,07",11/01/1994,1994,1994
01/12/1994,"3,80",12/01/1994,1994,1994
01/01/1995,"3,37",01/01/1995,1995,1995
01/02/1995,"3,25",02/01/1995,1995,1995
01/03/1995,"4,26",03/01/1995,1995,1995
01/04/1995,"4,26",04/01/1995,1995,1995
01/05/1995,"4,25",05/01/1995,1995,1995
01/06/1995,"4,04",06/01/1995,1995,1995
01/07/1995,"4,02",07/01/1995,1995,1995
01/08/1995,"3,84",08/01/1995,1995,1995
01/09/1995,"3,32",09/01/1995,1995,1995
01/10/1995,"3,09",10/01/1995,1995,1995
01/11/1995,"2,88",11/01/1995,1995,1995
01/12/1995,"2,78",12/01/1995,1995,1995
01/01/1996,"2,58",01/01/1996,1996,1996
01/02/1996,"2,35",02/01/1996,1996,1996
01/03/1996,"2,22",03/01/1996,1996,1996
01/04/1996,"2,07",04/01/1996,1996,1996
01/05/1996,"2,01",05/01/1996,1996,1996
01/06/1996,"1,98",06/01/1996,1996,1996
01/07/1996,"1,93",07/01/1996,1996,1996
01/08/1996,"1,97",08/01/1996,1996,1996
01/09/1996,"1,90",09/01/1996,1996,1996
01/10/1996,"1,86",10/01/1996,1996,1996
01/11/1996,"1,80",11/01/1996,1996,1996
01/12/1996,"1,80",12/01/1996,1996,1996
01/01/1997,"1,73",01/01/1997,1997,1997
01/02/1997,"1,67",02/01/1997,1997,1997
01/03/1997,"1,64",03/01/1997,1997,1997
01/04/1997,"1,66",04/01/1997,1997,1997
01/05/1997,"1,58",05/01/1997,1997,1997
01/06/1997,"1,61",06/01/1997,1997,1997
01/07/1997,"1,60",07/01/1997,1997,1997
01/08/1997,"1,59",08/01/1997,1997,1997
01/09/1997,"1,59",09/01/1997,1997,1997
01/10/1997,"1,67",10/01/1997,1997,1997
01/11/1997,"3,04",11/01/1997,1997,1997
01/12/1997,"2,97",12/01/1997,1997,1997
01/01/1998,"2,67",01/01/1998,1998,1998
01/02/1998,"2,13",02/01/1998,1998,1998
01/03/1998,"2,20",03/01/1998,1998,1998
01/04/1998,"1,71",04/01/1998,1998,1998
01/05/1998,"1,63",05/01/1998,1998,1998
01/06/1998,"1,60",06/01/1998,1998,1998
01/07/1998,"1,70",07/01/1998,1998,1998
01/08/1998,"1,48",08/01/1998,1998,1998
01/09/1998,"2,49",09/01/1998,1998,1998
01/10/1998,"2,94",10/01/1998,1998,1998
01/11/1998,"2,63",11/01/1998,1998,1998
01/12/1998,"2,40",12/01/1998,1998,1998
01/01/1999,"2,18",01/01/1999,1999,1999
01/02/1999,"2,38",02/01/1999,1999,1999
01/03/1999,"3,33",03/01/1999,1999,1999
01/04/1999,"2,35",04/01/1999,1999,1999
01/05/1999,"2,02",05/01/1999,1999,1999
01/06/1999,"1,67",06/01/1999,1999,1999
01/07/1999,"1,66",07/01/1999,1999,1999
01/08/1999,"1,57",08/01/1999,1999,1999
01/09/1999,"1,49",09/01/1999,1999,1999
01/10/1999,"1,38",10/01/1999,1999,1999
01/11/1999,"1,39",11/01/1999,1999,1999
01/12/1999,"1,60",12/01/1999,1999,1999
01/01/2000,"1,46",01/01/2000,2000,2000
01/02/2000,"1,45",02/01/2000,2000,2000
01/03/2000,"1,45",03/01/2000,2000,2000
01/04/2000,"1,30",04/01/2000,2000,2000
01/05/2000,"1,49",05/01/2000,2000,2000
01/06/2000,"1,39",06/01/2000,2000,2000
01/07/2000,"1,31",07/01/2000,2000,2000
01/08/2000,"1,41",08/01/2000,2000,2000
01/09/2000,"1,22",09/01/2000,2000,2000
01/10/2000,"1,29",10/01/2000,2000,2000
01/11/2000,"1,22",11/01/2000,2000,2000
01/12/2000,"1,20",12/01/2000,2000,2000
01/01/2001,"1,27",01/01/2001,2001,2001
01/02/2001,"1,02",02/01/2001,2001,2001
01/03/2001,"1,26",03/01/2001,2001,2001
01/04/2001,"1,19",04/01/2001,2001,2001
01/05/2001,"1,34",05/01/2001,2001,2001
01/06/2001,"1,27",06/01/2001,2001,2001
01/07/2001,"1,50",07/01/2001,2001,2001
01/08/2001,"1,60",08/01/2001,2001,2001
01/09/2001,"1,32",09/01/2001,2001,2001
01/10/2001,"1,53",10/01/2001,2001,2001
01/11/2001,"1,39",11/01/2001,2001,2001
01/12/2001,"1,39",12/01/2001,2001,2001
01/01/2002,"1,53",01/01/2002,2002,2002
01/02/2002,"1,25",02/01/2002,2002,2002
01/03/2002,"1,37",03/01/2002,2002,2002
01/04/2002,"1,48",04/01/2002,2002,2002
01/05/2002,"1,41",05/01/2002,2002,2002
01/06/2002,"1,33",06/01/2002,2002,2002
01/07/2002,"1,54",07/01/2002,2002,2002
01/08/2002,"1,44",08/01/2002,2002,2002
01/09/2002,"1,38",09/01/2002,2002,2002
01/10/2002,"1,65",10/01/2002,2002,2002
01/11/2002,"1,54",11/01/2002,2002,2002
01/12/2002,"1,74",12/01/2002,2002,2002
01/01/2003,"1,97",01/01/2003,2003,2003
01/02/2003,"1,83",02/01/2003,2003,2003
01/03/2003,"1,78",03/01/2003,2003,2003
01/04/2003,"1,87",04/01/2003,2003,2003
01/05/2003,"1,97",05/01/2003,2003,2003
01/06/2003,"1,86",06/01/2003,2003,2003
01/07/2003,"2,08",07/01/2003,2003,2003
01/08/2003,"1,77",08/01/2003,2003,2003
01/09/2003,"1,68",09/01/2003,2003,2003
01/10/2003,"1,64",10/01/2003,2003,2003
01/11/2003,"1,34",11/01/2003,2003,2003
01/12/2003,"1,37",12/01/2003,2003,2003
01/01/2004,"1,27",01/01/2004,2004,2004
01/02/2004,"1,08",02/01/2004,2004,2004
01/03/2004,"1,38",03/01/2004,2004,2004
01/04/2004,"1,18",04/01/2004,2004,2004
01/05/2004,"1,23",05/01/2004,2004,2004
01/06/2004,"1,23",06/01/2004,2004,2004
01/07/2004,"1,29",07/01/2004,2004,2004
01/08/2004,"1,29",08/01/2004,2004,2004
01/09/2004,"1,25",09/01/2004,2004,2004
01/10/2004,"1,21",10/01/2004,2004,2004
01/11/2004,"1,25",11/01/2004,2004,2004
01/12/2004,"1,48",12/01/2004,2004,2004
01/01/2005,"1,38",01/01/2005,2005,2005
01/02/2005,"1,22",02/01/2005,2005,2005
01/03/2005,"1,53",03/01/2005,2005,2005
01/04/2005,"1,41",04/01/2005,2005,2005
01/05/2005,"1,50",05/01/2005,2005,2005
01/06/2005,"1,59",06/01/2005,2005,2005
01/07/2005,"1,51",07/01/2005,2005,2005
01/08/2005,"1,66",08/01/2005,2005,2005
01/09/2005,"1,50",09/01/2005,2005,2005
01/10/2005,"1,41",10/01/2005,2005,2005
01/11/2005,"1,38",11/01/2005,2005,2005
01/12/2005,"1,47",12/01/2005,2005,2005
01/01/2006,"1,43",01/01/2006,2006,2006
01/02/2006,"1,15",02/01/2006,2006,2006
01/03/2006,"1,42",03/01/2006,2006,2006
01/04/2006,"1,08",04/01/2006,2006,2006
01/05/2006,"1,28",05/01/2006,2006,2006
01/06/2006,"1,18",06/01/2006,2006,2006
01/07/2006,"1,17",07/01/2006,2006,2006
01/08/2006,"1,26",08/01/2006,2006,2006
01/09/2006,"1,06",09/01/2006,2006,2006
01/10/2006,"1,09",10/01/2006,2006,2006
01/11/2006,"1,02",11/01/2006,2006,2006
01/12/2006,"0,99",12/01/2006,2006,2006
01/01/2007,"1,08",01/01/2007,2007,2007
01/02/2007,"0,87",02/01/2007,2007,2007
01/03/2007,"1,05",03/01/2007,2007,2007
01/04/2007,"0,94",04/01/2007,2007,2007
01/05/2007,"1,03",05/01/2007,2007,2007
01/06/2007,"0,91",06/01/2007,2007,2007
01/07/2007,"0,97",07/01/2007,2007,2007
01/08/2007,"0,99",08/01/2007,2007,2007
01/09/2007,"0,80",09/01/2007,2007,2007
01/10/2007,"0,93",10/01/2007,2007,2007
01/11/2007,"0,84",11/01/2007,2007,2007
01/12/2007,"0,84",12/01/2007,2007,2007
01/01/2008,"0,93",01/01/2008,2008,2008
01/02/2008,"0,80",02/01/2008,2008,2008
01/03/2008,"0,84",03/01/2008,2008,2008
01/04/2008,"0,90",04/01/2008,2008,2008
01/05/2008,"0,88",05/01/2008,2008,2008
01/06/2008,"0,96",06/01/2008,2008,2008
01/07/2008,"1,07",07/01/2008,2008,2008
01/08/2008,"1,02",08/01/2008,2008,2008
01/09/2008,"1,10",09/01/2008,2008,2008
01/10/2008,"1,18",10/01/2008,2008,2008
01/11/2008,"1,02",11/01/2008,2008,2008
01/12/2008,"1,12",12/01/2008,2008,2008
01/01/2009,"1,05",01/01/2009,2009,2009
01/02/2009,"0,86",02/01/2009,2009,2009
01/03/2009,"0,97",03/01/2009,2009,2009
01/04/2009,"0,84",04/01/2009,2009,2009
01/05/2009,"0,77",05/01/2009,2009,2009
01/06/2009,"0,76",06/01/2009,2009,2009
01/07/2009,"0,79",07/01/2009,2009,2009
01/08/2009,"0,69",08/01/2009,2009,2009
01/09/2009,"0,69",09/01/2009,2009,2009
01/10/2009,"0,69",10/01/2009,2009,2009
01/11/2009,"0,66",11/01/2009,2009,2009
01/12/2009,"0,73",12/01/2009,2009,2009
01/01/2010,"0,66",01/01/2010,2010,2010
01/02/2010,"0,59",02/01/2010,2010,2010
01/03/2010,"0,76",03/01/2010,2010,2010
01/04/2010,"0,67",04/01/2010,2010,2010
01/05/2010,"0,75",05/01/2010,2010,2010
01/06/2010,"0,79",06/01/2010,2010,2010
01/07/2010,"0,86",07/01/2010,2010,2010
01/08/2010,"0,89",08/01/2010,2010,2010
01/09/2010,"0,85",09/01/2010,2010,2010
01/10/2010,"0,81",10/01/2010,2010,2010
01/11/2010,"0,81",11/01/2010,2010,2010
01/12/2010,"0,93",12/01/2010,2010,2010
01/01/2011,"0,86",01/01/2011,2011,2011
01/02/2011,"0,84",02/01/2011,2011,2011
01/03/2011,"0,92",03/01/2011,2011,2011
01/04/2011,"0,84",04/01/2011,2011,2011
01/05/2011,"0,99",05/01/2011,2011,2011
01/06/2011,"0,96",06/01/2011,2011,2011
01/07/2011,"0,97",07/01/2011,2011,2011
01/08/2011,"1,07",08/01/2011,2011,2011
01/09/2011,"0,94",09/01/2011,2011,2011
01/10/2011,"0,88",10/01/2011,2011,2011
01/11/2011,"0,86",11/01/2011,2011,2011
01/12/2011,"0,91",12/01/2011,2011,2011
01/01/2012,"0,89",01/01/2012,2012,2012
01/02/2012,"0,75",02/01/2012,2012,2012
01/03/2012,"0,82",03/01/2012,2012,2012
01/04/2012,"0,71",04/01/2012,2012,2012
01/05/2012,"0,74",05/01/2012,2012,2012
01/06/2012,"0,64",06/01/2012,2012,2012
01/07/2012,"0,68",07/01/2012,2012,2012
01/08/2012,"0,69",08/01/2012,2012,2012
01/09/2012,"0,54",09/01/2012,2012,2012
01/10/2012,"0,61",10/01/2012,2012,2012
01/11/2012,"0,55",11/01/2012,2012,2012
01/12/2012,"0,55",12/01/2012,2012,2012
01/01/2013,"0,60",01/01/2013,2013,2013
01/02/2013,"0,49",02/01/2013,2013,2013
01/03/2013,"0,55",03/01/2013,2013,2013
01/04/2013,"0,61",04/01/2013,2013,2013
01/05/2013,"0,60",05/01/2013,2013,2013
01/06/2013,"0,61",06/01/2013,2013,2013
01/07/2013,"0,72",07/01/2013,2013,2013
01/08/2013,"0,71",08/01/2013,2013,2013
01/09/2013,"0,71",09/01/2013,2013,2013
01/10/2013,"0,81",10/01/2013,2013,2013
01/11/2013,"0,72",11/01/2013,2013,2013
01/12/2013,"0,79",12/01/2013,2013,2013
01/01/2014,"0,85",01/01/2014,2014,2014
01/02/2014,"0,79",02/01/2014,2014,2014
01/03/2014,"0,77",03/01/2014,2014,2014
01/04/2014,"0,82",04/01/2014,2014,2014
01/05/2014,"0,87",05/01/2014,2014,2014
01/06/2014,"0,82",06/01/2014,2014,2014
01/07/2014,"0,95",07/01/2014,2014,2014
01/08/2014,"0,87",08/01/2014,2014,2014
01/09/2014,"0,91",09/01/2014,2014,2014
01/10/2014,"0,95",10/01/2014,2014,2014
01/11/2014,"0,84",11/01/2014,2014,2014
01/12/2014,"0,96",12/01/2014,2014,2014
01/01/2015,"0,94",01/01/2015,2015,2015
01/02/2015,"0,82",02/01/2015,2015,2015
01/03/2015,"1,04",03/01/2015,2015,2015
01/04/2015,"0,95",04/01/2015,2015,2015
01/05/2015,"0,99",05/01/2015,2015,2015
01/06/2015,"1,07",06/01/2015,2015,2015
01/07/2015,"1,18",07/01/2015,2015,2015
01/08/2015,"1,11",08/01/2015,2015,2015
01/09/2015,"1,11",09/01/2015,2015,2015
01/10/2015,"1,11",10/01/2015,2015,2015
01/11/2015,"1,06",11/01/2015,2015,2015
01/12/2015,"1,16",12/01/2015,2015,2015
01/01/2016,"1,06",01/01/2016,2016,2016
01/02/2016,"1,00",02/01/2016,2016,2016
01/03/2016,"1,16",03/01/2016,2016,2016
01/04/2016,"1,06",04/01/2016,2016,2016
01/05/2016,"1,11",05/01/2016,2016,2016
01/06/2016,"1,16",06/01/2016,2016,2016
01/07/2016,"1,11",07/01/2016,2016,2016
01/08/2016,"1,22",08/01/2016,2016,2016
01/09/2016,"1,11",09/01/2016,2016,2016
01/10/2016,"1,05",10/01/2016,2016,2016
01/11/2016,"1,04",11/01/2016,2016,2016
01/12/2016,"1,12",12/01/2016,2016,2016
01/01/2017,"1,09",01/01/2017,2017,2017
01/02/2017,"0,87",02/01/2017,2017,2017
01/03/2017,"1,05",03/01/2017,2017,2017
01/04/2017,"0,79",04/01/2017,2017,2017
01/05/2017,"0,93",05/01/2017,2017,2017
01/06/2017,"0,81",06/01/2017,2017,2017
01/07/2017,"0,80",07/01/2017,2017,2017
01/08/2017,"0,80",08/01/2017,2017,2017
01/09/2017,"0,64",09/01/2017,2017,2017
01/10/2017,"0,64",10/01/2017,2017,2017
01/11/2017,"0,57",11/01/2017,2017,2017
01/12/2017,"0,54",12/01/2017,2017,2017
01/01/2018,"0,58",01/01/2018,2018,2018
01/02/2018,"0,47",02/01/2018,2018,2018
01/03/2018,"0,53",03/01/2018,2018,2018
01/04/2018,"0,52",04/01/2018,2018,2018
01/05/2018,"0,52",05/01/2018,2018,2018
01/06/2018,"0,52",06/01/2018,2018,2018
01/07/2018,"0,54",07/01/2018,2018,2018
01/08/2018,"0,57",08/01/2018,2018,2018
01/09/2018,"0,47",09/01/2018,2018,2018
01/10/2018,"0,54",10/01/2018,2018,2018
01/11/2018,"0,49",11/01/2018,2018,2018
01/12/2018,"0,49",12/01/2018,2018,2018
01/01/2019,"0,54",01/01/2019,2019,2019
01/02/2019,"0,37",02/01/2019,2019,2019

## WithColumn 2/2

In [ ]:
# 1. Criar um dataframe para ler o arquivo no HDFS /user/<nome/data/juros_selic/juros_selic

In [47]:
df_juros = spark.read.csv("/user/daniel/data/exercises-data/juros_selic/juros_selic", sep=";", header="True")

In [48]:
df_juros.show(5)

+----------+-----+
|      data|valor|
+----------+-----+
|01/06/1986| 1,27|
|01/07/1986| 1,95|
|01/08/1986| 2,57|
|01/09/1986| 2,94|
|01/10/1986| 1,96|
+----------+-----+
only showing top 5 rows

In [ ]:
# 2. Agrupar todas as datas pelo ano em ordem decrescente e salvar a quantidade de meses ocorridos, o valor médio, mínimo e máximo do campo valor com a seguinte estrutura:

In [57]:
df_juros_ano = df_juros.withColumn("ano", from_unixtime(unix_timestamp(col("data"), "dd/MM/yyyy"),"yyyy"))
df_juros_ano_mes = df_juros_ano.withColumn("mes", from_unixtime(unix_timestamp(col("data"), "dd/MM/yyyy"),"MM"))

In [66]:
df_juros_ano_mes_valor = df_juros_ano_mes.withColumn("valor", regexp_replace(col("valor"), "\.", ""))
df_juros_ano_mes_valor = df_juros_ano_mes_valor.withColumn("valor", regexp_replace(col("valor"), "\,", "."))

In [69]:
df_juros_ano_mes_valor = df_juros_ano_mes_valor.withColumn("valor", col("valor").cast(FloatType()))

In [70]:
df_juros_ano_mes_valor.show(5)

+----------+-----+----+---+
|      data|valor| ano|mes|
+----------+-----+----+---+
|01/06/1986| 1.27|1986| 06|
|01/07/1986| 1.95|1986| 07|
|01/08/1986| 2.57|1986| 08|
|01/09/1986| 2.94|1986| 09|
|01/10/1986| 1.96|1986| 10|
+----------+-----+----+---+
only showing top 5 rows

In [73]:
df_juros_ano_mes_valor.printSchema()

root
 |-- data: string (nullable = true)
 |-- valor: float (nullable = true)
 |-- ano: string (nullable = true)
 |-- mes: string (nullable = true)

In [103]:
from pyspark.sql.functions import count, avg, min, max, desc, format_number

In [98]:
df_juros_ano_mes_valor.groupBy("ano").agg(count("mes").alias("Meses"),
                                          avg("valor").cast("decimal(38,2)").alias("Valor Médio"),
                                          min("valor").cast("decimal(38,2)").alias("Valor Mínimo"),
                                          max("valor").cast("decimal(38,2)").alias("Valor Máximo")
                                         ).sort(desc("ano")).show()

+----+-----+-----------+------------+------------+
| ano|Meses|Valor Médio|Valor Mínimo|Valor Máximo|
+----+-----+-----------+------------+------------+
|2019|    2|       0.46|        0.37|        0.54|
|2018|   12|       0.52|        0.47|        0.58|
|2017|   12|       0.79|        0.54|        1.09|
|2016|   12|       1.10|        1.00|        1.22|
|2015|   12|       1.04|        0.82|        1.18|
|2014|   12|       0.87|        0.77|        0.96|
|2013|   12|       0.66|        0.49|        0.81|
|2012|   12|       0.68|        0.54|        0.89|
|2011|   12|       0.92|        0.84|        1.07|
|2010|   12|       0.78|        0.59|        0.93|
|2009|   12|       0.79|        0.66|        1.05|
|2008|   12|       0.98|        0.80|        1.18|
|2007|   12|       0.94|        0.80|        1.08|
|2006|   12|       1.18|        0.99|        1.43|
|2005|   12|       1.46|        1.22|        1.66|
|2004|   12|       1.26|        1.08|        1.48|
|2003|   12|       1.76|        1.34|        2.08|
|2002|   12|       1.47|        1.25|        1.74|
|2001|   12|       1.34|        1.02|        1.60|
|2000|   12|       1.35|        1.20|        1.49|
+----+-----+-----------+------------+------------+
only showing top 20 rows

In [105]:
df_juros_ano_mes_valor.groupBy("ano").agg(count("mes").alias("Meses"),
                                          format_number(avg("valor"),2).alias("Valor Médio"),
                                          format_number(min("valor"),2).alias("Valor Mínimo"),
                                          format_number(max("valor"),2).alias("Valor Máximo")
                                         ).sort(desc("ano")).show()

+----+-----+-----------+------------+------------+
| ano|Meses|Valor Médio|Valor Mínimo|Valor Máximo|
+----+-----+-----------+------------+------------+
|2019|    2|       0.46|        0.37|        0.54|
|2018|   12|       0.52|        0.47|        0.58|
|2017|   12|       0.79|        0.54|        1.09|
|2016|   12|       1.10|        1.00|        1.22|
|2015|   12|       1.04|        0.82|        1.18|
|2014|   12|       0.87|        0.77|        0.96|
|2013|   12|       0.66|        0.49|        0.81|
|2012|   12|       0.68|        0.54|        0.89|
|2011|   12|       0.92|        0.84|        1.07|
|2010|   12|       0.78|        0.59|        0.93|
|2009|   12|       0.79|        0.66|        1.05|
|2008|   12|       0.98|        0.80|        1.18|
|2007|   12|       0.94|        0.80|        1.08|
|2006|   12|       1.18|        0.99|        1.43|
|2005|   12|       1.46|        1.22|        1.66|
|2004|   12|       1.26|        1.08|        1.48|
|2003|   12|       1.76|        1.34|        2.08|
|2002|   12|       1.47|        1.25|        1.74|
|2001|   12|       1.34|        1.02|        1.60|
|2000|   12|       1.35|        1.20|        1.49|
+----+-----+-----------+------------+------------+
only showing top 20 rows

In [ ]:
# 3. Salvar no hdfs:///user/<nome>/relatorioAnual com compressão zlib e formato orc

In [99]:
df_juros_ano_mes_valor.write.orc("/user/daniel/relatorioAnual", compression="zlib")

In [101]:
! hdfs dfs -ls /user/daniel/relatorioAnual

Found 2 items
-rw-r--r--   2 root supergroup          0 2022-07-06 01:30 /user/daniel/relatorioAnual/_SUCCESS
-rw-r--r--   2 root supergroup       2535 2022-07-06 01:30 /user/daniel/relatorioAnual/part-00000-a86213f8-f8a4-446c-b50a-1c6888291752-c000.zlib.orc